services:
  grafana:
    image: grafana/grafana:latest
    container_name: eris_predict_grafana
    restart: unless-stopped
    ports:
      - 3000:3000
#    volumes:
#      - ./docker/grafana/datas/data:/var/lib/grafana
#      - ./docker/grafana/datas/config:/etc/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: eris_predict_prometheus
    restart: unless-stopped
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      TZ: Europe/Paris
