# docker-compose.yml


services:
  api:
    build: .
    container_name: eris_predict_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./logfiles:/app/logfiles
      - ./api:/app/api
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - ENABLE_METRICS=true
    restart: unless-stopped
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: eris_predict_grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # DÃ©finit le mot de passe admin

    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
          - api
          - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: eris_predict_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

volumes:
  grafana_data:
  prometheus-data: